variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:win10:stable:
  tags:
    - win10
  script:
    - rustc --version; cargo --version
    - cargo +stable test --all --verbose

test:win10:beta:
  tags:
    - win10
  script:
    - rustc --version; cargo --version
    - cargo +beta test --all --verbose

test:win10:1.29.0:
  tags:
    - win10
  script:
    - rustc --version; cargo --version
    - cargo +1.29.0 test --all --verbose
    
build:mingw:x86_x64:
  variables:
    ARCH: "x86_64"
  tags:
    - docker
  image: rust:latest
  script:
    - apt-get update
    - apt-get install mingw-w64 -y
    - rustup target install $ARCH-pc-windows-gnu
    - cp /usr/$ARCH-w64-mingw32/lib/crt2.o $RUSTUP_HOME/toolchains/*-x86_64-unknown-linux-gnu/lib/rustlib/$ARCH-pc-windows-gnu/lib/
    - rustc --version --verbose; cargo --version --verbose
    - cargo test --no-run --target $ARCH-pc-windows-gnu --all --verbose
