[package]
name = "winlog"
version = "0.1.0"
authors = ["Jeroen C. van Gelderen <jeroen@vangelderen.org>"]
edition = "2018"
build = "build.rs"
categories = [ "development-tools::debugging", "os::windows-apis" ]
description = "A simple Rust log backend to send messages to the Windows event log."
documentation = "https://gitlab.com/arbitrix/winlog"
homepage = "https://gitlab.com/arbitrix/winlog"
repository = "https://gitlab.com/arbitrix/winlog"
keywords = [ "eventlog", "logging", "windows" ]
license = "MIT OR Apache-2.0"
readme = "README.md"

[build-dependencies]
regex = "1.0"

[dev-dependencies]
rand = "0.5"

[dependencies]
log = { version = "0.4", features = [ "std" ] }
widestring = "0.4"
winapi = { version = "0.3", features = [ "winbase" ] }
winreg = "0.5"
